### ISSUE TITLE
Can't build the project.

### ISSUE THREAD

**Issue by omsharp** [Geeksltd/VSIX.SmartFinder#1]
I'm trying to build with VS2017, but I get this error:

Schema validation error for 'D:\VS\VSIX.SmartFinder\Geeks.SmartFinder\obj\Debug\extension.vsixmanifest'. Encountered an error when opening the vsixmanifest schema. Could not find a part of the path 'D:\VS\VSIX.SmartFinder\packages\Microsoft.VSSDK.BuildTools.16.0.2264\tools\VSSDK\schemas\v3\PackageManifestSchema.xsd'.	Geeks.SmartFinder	D:\VS\VSIX.SmartFinder\Geeks.SmartFinder\VSSDK		

![image](https://user-images.githubusercontent.com/1245060/81249030-f52c6480-901d-11ea-8ff0-7f2b66624b15.png)

Any idea on the error or how to resolve it?

**Comment by omsharp** [comment]
Ok, never mind. I solved the issue.

**Comment by bert2** [comment]
@omsharp do you remember what you did to fix it?

**Comment by omsharp** [comment]
@bert2 
Sorry mate. I have no clue. I don't even remember opening this issue.
It was long time ago.
